#cloud-config
users:
  - name: hebcal
    gecos: Hebcal
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-dss AAAAB3NzaC1kc3MAAAEBAKCDECinh9zUhHeKibZAumzTqk9MA0VVJJ4EH2Uf2wc1qXZlEA5d6k8LLc7FUZWQ8bn+4BjDEtXlzxAS/t3SmdFJCwaRhzu/5FDZi9usLCCbWsYgUos//uOD37Wpg0fkgIMVi/Jc0L8KceoHACuA9ORV9EIzmvvIFiz8ONKurRilGyL2QMncEN52MQgShv6nhAdFHk99/JAYY7SLhzy8UNBUQunpBJfNNGCHN+IPLMo7hiq5AfQxSHpo6dYeSLRJdWg76CMCf//VC7E/i+6ucHGsO/ZpZ3XVCP7dvt/U1j6qLcm0LWO0n3JrlrEOx9pwGgqyEopoeAaOrXgpydBxm/MAAAAVAIjvZ2FF09u4SQ+LuyQlIMfLB3HVAAABADR6tZndAMf/1p88jwc+Bo5wTglcPkktEXCxPMwrM5/WB6GCFsVGAZsn4/yOq8/Bijgy+RzKZT1is678Jk6Y+Ux1jTv8fjvKzSXn5G6/PT71ayElyKxo3WUTP5m0tnbwLXGBSJz1FfAGv7LHLC7+Crn+1Mlu0N4+JAoxd/C2xK/A1UdeeCwdfHOTuHB0wYEvf0vBSv+6qCv3aKC8cu6kstemijMCCXLPnK0uwls/1lgseeZCz2fOcW1N6kQgrSddHfyqQrQS1Zw22fRYepAYKPUmx3AcFJ6pWp3nZq7eboTRqzcJ8WL1LTrBnArZ/H7u974AuWE2u5hF50k38J8zvJEAAAEAZg9HmKsR/tEGah899pMSCpuTxrVcI3P969qbNq6i4na7S8UE2jd36Vs+bseibHlH+cTm9Fdtey990RuKklBoXlDovOKrmQ2dpzcIDUDyrAs/uRxVHqeZ8KKg9VDsf6xf0kHMX5sCFlge085o8c3AS+bu/pYLRlUpx8LGmshy9HNbHSoU4iAsB/EdRtSnor3vaZozHurPiVM7UwgW9w+C4aK5eQoHL45tTrDefDRCHn+b1w7ZTnEqM/vpHtpBvsN3FErnPVPmTuWl+EBNFRoNE5TzMcBJMa3p80t23VGaa+0mbNPE6VlIzbkXP1jZdw2sEpvE/UxdOnTnN9QAY8g9UA== mradwin@michael-radwins-computer.local
  - name: mradwin
    gecos: Michael J. Radwin
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-dss AAAAB3NzaC1kc3MAAAEBAKCDECinh9zUhHeKibZAumzTqk9MA0VVJJ4EH2Uf2wc1qXZlEA5d6k8LLc7FUZWQ8bn+4BjDEtXlzxAS/t3SmdFJCwaRhzu/5FDZi9usLCCbWsYgUos//uOD37Wpg0fkgIMVi/Jc0L8KceoHACuA9ORV9EIzmvvIFiz8ONKurRilGyL2QMncEN52MQgShv6nhAdFHk99/JAYY7SLhzy8UNBUQunpBJfNNGCHN+IPLMo7hiq5AfQxSHpo6dYeSLRJdWg76CMCf//VC7E/i+6ucHGsO/ZpZ3XVCP7dvt/U1j6qLcm0LWO0n3JrlrEOx9pwGgqyEopoeAaOrXgpydBxm/MAAAAVAIjvZ2FF09u4SQ+LuyQlIMfLB3HVAAABADR6tZndAMf/1p88jwc+Bo5wTglcPkktEXCxPMwrM5/WB6GCFsVGAZsn4/yOq8/Bijgy+RzKZT1is678Jk6Y+Ux1jTv8fjvKzSXn5G6/PT71ayElyKxo3WUTP5m0tnbwLXGBSJz1FfAGv7LHLC7+Crn+1Mlu0N4+JAoxd/C2xK/A1UdeeCwdfHOTuHB0wYEvf0vBSv+6qCv3aKC8cu6kstemijMCCXLPnK0uwls/1lgseeZCz2fOcW1N6kQgrSddHfyqQrQS1Zw22fRYepAYKPUmx3AcFJ6pWp3nZq7eboTRqzcJ8WL1LTrBnArZ/H7u974AuWE2u5hF50k38J8zvJEAAAEAZg9HmKsR/tEGah899pMSCpuTxrVcI3P969qbNq6i4na7S8UE2jd36Vs+bseibHlH+cTm9Fdtey990RuKklBoXlDovOKrmQ2dpzcIDUDyrAs/uRxVHqeZ8KKg9VDsf6xf0kHMX5sCFlge085o8c3AS+bu/pYLRlUpx8LGmshy9HNbHSoU4iAsB/EdRtSnor3vaZozHurPiVM7UwgW9w+C4aK5eQoHL45tTrDefDRCHn+b1w7ZTnEqM/vpHtpBvsN3FErnPVPmTuWl+EBNFRoNE5TzMcBJMa3p80t23VGaa+0mbNPE6VlIzbkXP1jZdw2sEpvE/UxdOnTnN9QAY8g9UA== mradwin@michael-radwins-computer.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoHvNAA5UBj4DpCZsTtjjX82mM2eBECmc6wGXtZeaeqxyBdJBkkDfPmZwwL6OfCceoGHvU4zPEvonFFkjgDwRQYItVnYA4LolgbAjTVf0Bi+dv7Ny8B4fuMin0GvdrCs3BiX018Dw0za5UlopHESPHTKyAOAovR0tftQ+AzAFzae6ac/zZHK0odvoqWROlxSxOJZZl61EVM42ExYOSKm5tsc3g/ObW4wtaMOKUFHGFHfeeSRzYy1kacPVwIbEKTRCh8gLrL3yfOW/un6XF0U9eB+cqE0mVASWTOY59V7EWMJnUZaQcB8yZDeSF/iNEnB2e6ewUMo5X4nqYTaofTUjv mradwin@MTVL12027dd2a
  - name: nagios
    gecos: Nagios
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkIbumcez+ggabZq5wJwgA226Q09hG2AT45+epPdXL4KpEn46kb3ZF1Gk1QTUQhMUiDQaoHUGwUSAxGUcC/dOfDkBPHfpDLNZylvGzDMjLg8lvw1/IQC2XbCmDTqZ13Dqc2dnex9hN+N7NimnqaaGW0rvIDjlz27r0tr7N66oXTvPsWItahBQowSkr+agoCLeWxzjKUAabZJ38yp6TNFjU53WadiFGSF7gVjBhGId7F8ukSu2yYl/0i6isU3VK72q7AfKcp/n0dcm1t+BsQKJjH6AY1lmf5R6ZO2qAlRorzpYMzlK5A5VYcp4ILgKSTWKnFNHoP508/4UjD9Pt7uoL nagios@hebcalmonitor

debconf_selections: |     # Need to perserve newlines
    unattended-upgrades unattended-upgrades/enable_auto_updates boolean true
    postfix postfix/main_mailer_type select Satellite system
    postfix postfix/mailname string hebcal.com
    postfix postfix/relayhost string [email-smtp.us-east-1.amazonaws.com]:25

package_upgrade: true

packages:
  - bsd-mailx
  - g++
  - gcc
  - git
  - iptables-persistent
  - libsasl2-modules
  - make
  - monitoring-plugins-basic
  - netfilter-persistent
  - postfix
  - sqlite3
  - sysstat
  - unattended-upgrades
  - unzip

write_files:
  - path: /etc/mailname
    permissions: '0644'
    content: |
      hebcal.com
  - path: /etc/default/sysstat
    permissions: '0644'
    content: |
      ENABLED="true"
  - path: /etc/systemd/system/koa.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Hebcal Koa Web Server
      After=network.target
      [Service]
      Type=simple
      # set the working directory to have consistent relative paths
      WorkingDirectory=/var/www
      # start the server file (file is relative to WorkingDirectory here)
      ExecStart=/usr/bin/node /var/www/dist/app-www.js
      # if process crashes, always try to restart
      Restart=always
      # let 500ms between the crash and the restart
      RestartSec=500ms
      # send log to syslog here (it doesn't compete with other log config in the app itself)
      StandardOutput=syslog
      StandardError=syslog
      # nodejs process name in syslog
      SyslogIdentifier=koa
      # user and group starting the app
      User=www-data
      Group=www-data
      # set the environement (dev, prod)
      Environment=NODE_ENV=production
      [Install]
      # start node at multi user system level (= sysVinit runlevel 3) 
      WantedBy=multi-user.target
  - path: /etc/logrotate.d/hebcal-koa
    permissions: '0644'
    content: |
      /var/log/hebcal/*.log {
        su root
        daily
        rotate 7
        delaycompress
        compress
        notifempty
        missingok
        postrotate
           kill -HUP `cat /var/log/hebcal/koa.pid`
        endscript
      }
  - path: /etc/postfix/main.cf
    permissions: '0644'
    content: |
      smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
      biff = no
      append_dot_mydomain = no
      readme_directory = no
      compatibility_level = 2
      smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      smtpd_tls_security_level=may
      smtp_use_tls = yes
      smtp_tls_security_level = encrypt
      smtp_tls_note_starttls_offer = yes
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
      smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
      smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
      myhostname = localhost
      alias_maps = hash:/etc/aliases
      alias_database = hash:/etc/aliases
      myorigin = /etc/mailname
      mydestination = 
      mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
      mailbox_size_limit = 0
      recipient_delimiter = +
      inet_interfaces = loopback-only
      inet_protocols = all
      relayhost = [email-smtp.us-east-1.amazonaws.com]:25
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options = noanonymous
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
  - path: /tmp/zips-dummy.sql
    permissions: '0644'
    content: |
      CREATE TABLE ZIPCodes_Primary (
      ZipCode char(5) NOT NULL PRIMARY KEY,
      CityMixedCase varchar(35) NULL,
      State char(2),
      Latitude decimal(12, 6),
      Longitude decimal(12, 6),
      TimeZone char(2) NULL,
      DayLightSaving char(1) NULL
      );

runcmd:
  - service netfilter-persistent flush
  - iptables -F
  - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -A INPUT -p tcp --dport ssh -j ACCEPT
  - iptables -A INPUT -p tcp --dport http -j ACCEPT
  - iptables -A INPUT -p tcp --dport https -j ACCEPT
  - iptables -A INPUT -p icmp -j ACCEPT
  - iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
  - iptables -A INPUT -j DROP
  - iptables -I INPUT 1 -i lo -j ACCEPT
  - service netfilter-persistent save
  - fallocate -l 1G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - swapon -s
  - free -m
  - echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
  - sysctl vm.swappiness=10
  - sysctl vm.vfs_cache_pressure=50
  - echo "vm.swappiness = 10" >> /etc/sysctl.conf
  - echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.conf
  - adduser mradwin hebcal
  - perl -pi -e 's/^.*PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - systemctl reload ssh.service
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt-get install -y nodejs
  - git clone https://github.com/hebcal/hebcal-web.git /home/hebcal/hebcal-web
  - cd /home/hebcal/hebcal-web && npm install
  - cd /home/hebcal/hebcal-web && npm run build
  - mkdir -p /var/www
  - cd /home/hebcal/hebcal-web && npm run deploy
  - curl -o /tmp/countryInfo.txt http://download.geonames.org/export/dump/countryInfo.txt
  - curl -o /tmp/admin1CodesASCII.txt http://download.geonames.org/export/dump/admin1CodesASCII.txt
  - curl -o /tmp/cities5000.zip http://download.geonames.org/export/dump/cities5000.zip
  - curl -o /tmp/IL.zip http://download.geonames.org/export/dump/IL.zip
  - cd /tmp && unzip cities5000.zip
  - cd /tmp && unzip IL.zip
  - mkdir --mode=0775 /var/log/hebcal
  - chown www-data:hebcal /var/log/hebcal
  - chown -R hebcal:hebcal /home/hebcal
  - sqlite3 -echo /var/www/zips.sqlite3 < /tmp/zips-dummy.sql
  - cd /home/hebcal/hebcal-web && npx build-geonames-sqlite /var/www/geonames.sqlite3 /tmp/countryInfo.txt /tmp/cities5000.txt /home/hebcal/hebcal-web/node_modules/@hebcal/geo-sqlite/cities-patch.txt /tmp/admin1CodesASCII.txt /tmp/IL.txt
  - systemctl enable koa.service
  - systemctl start koa.service
  - mkdir -p /var/www/html
  - curl -v -o /var/www/html/favicon.ico https://www.hebcal.com/favicon.ico
  - curl -v -o /var/www/html/robots.txt https://www.hebcal.com/robots.txt
